# Generated by Django 2.1 on 2019-01-08 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_patient', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(16)], verbose_name='Index Patient')),
                ('nom_patient', models.CharField(max_length=128, verbose_name='Nom Patient')),
                ('num_dossier', models.CharField(max_length=64, verbose_name='Numero Dossier')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
            ],
        ),
    ]
