# Generated by Django 2.1 on 2019-02-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190108_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_worklist', models.DateField(auto_now=True, verbose_name='Date Worklist')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='index_patient',
            field=models.PositiveIntegerField(unique=True, verbose_name='Index Patient'),
        ),
        migrations.AddField(
            model_name='worklist',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.archive', verbose_name='Archive'),
        ),
    ]
