# Generated by Django 2.1 on 2019-02-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190214_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='date_worklist',
            field=models.DateField(verbose_name='Date Worklist'),
        ),
    ]
