# Generated by Django 2.1 on 2019-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190214_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklist',
            name='archive',
        ),
        migrations.AddField(
            model_name='worklist',
            name='archive',
            field=models.ManyToManyField(to='app.archive', verbose_name='Archive'),
        ),
    ]
