# Generated by Django 2.1 on 2019-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190214_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='archive',
            field=models.ManyToManyField(related_name='archives', to='app.archive', verbose_name='Archive'),
        ),
    ]
